version: 2
updates:
#
#
# [GHAction]
# Based on https://github.com/yoanm/shared-config/blob/master/GitHub/dependabot/github-action.yml file
#
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday # Create PRs during week-ends, they will be ready on monday morning
    commit-message:
      prefix: '[dependabot][ghaction] - ' # No need to specify prod/dev for GHAction as there is only "production" updates !
      include: scope
    groups:
# Group all basic updates inside the a single PR
# No need to split prod/dev as there is only prod updates
      all-actions:
        applies-to: version-updates
        patterns: ['*']
# Group all security updates inside the a single PR
# No need to split prod/dev as there is only prod updates
# +Most likely no need to split major and other updates either
      SECURITY-all:
        applies-to: security-updates
        patterns: ['*']
#
#
# [Node] (npm / yarn)
# Based on https://github.com/yoanm/shared-config/blob/master/GitHub/dependabot/npm_yarn.yml file
#
  - package-ecosystem: npm
    directory: /
    schedule: # Create PRs during week-ends, they will be ready on monday morning
      interval: weekly
      day: sunday
    versioning-strategy: increase
    commit-message:
      prefix: '[dependabot][prod][npm] - '
      prefix-development: '[dependabot][dev][npm] - '
      include: scope
    groups:
# Split basic updates by:
#  - prod vs dev
#  - major vs minor vs patch (Node packages may not properly follow semver ....)
      prod-majors:
        applies-to: version-updates
        dependency-type: production
        update-types: ['major']
        patterns: ['*']
      prod-minors:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor']
        patterns: ['*']
      prod-others:
        applies-to: version-updates
        dependency-type: production
        patterns: ['*']
      dev-majors:
        applies-to: version-updates
        dependency-type: development
        update-types: ['major']
        patterns: ['*']
      dev-minors:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor']
        patterns: ['*']
      dev-others:
        applies-to: version-updates
        dependency-type: development
        patterns: ['*']
# Split security updates by:
#  - prod vs dev
      SECURITY-prod:
        applies-to: security-updates
        dependency-type: production
        patterns: ['*']
      SECURITY-dev:
        applies-to: security-updates
        dependency-type: development
        patterns: ['*']
