name: gha-versioning
description: |
  Create (or override existing) vX and vX.Y based on the provided tag. Useful to maintain GitHub Action tags up to date.
branding:
  icon: tag
  color: yellow

inputs:
  tag:
    description: The full tag used to generate vX and vX.Y tags
    required: true

outputs:
  minor-tag:
    description: Minor tag created (vX.Y)
    value: ${{ steps.build-outputs.outputs.groups }}
  major-tag:
    description: Major tag created (vX)
    value: ${{ steps.build-outputs.outputs.reports }}

runs:
  using: "composite"
  steps:
    # Even if an input is marked as "required", an empty value (or no value) may be passed !
    - shell: bash
      env:
        FULL_TAG: ${{ inputs.tag }}
      run: |
        # Validate provided tag ...
        if ! [[ "$FULL_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::error::Invalid tag format (expected vX.Y.Z) !"
          exit 1
        fi;

    - id: generate-tags
      shell: bash
      env:
        FULL_TAG: ${{ inputs.tag }}
      run: |
        # Generate vX and vX.Y tags
  
        MINOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1-2`;
        if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then
          echo "::error::Invalid minor tag format (expected vX.Y) !"
          exit 2
        fi;
        echo "Minor tag -> $MINOR_TAG"
        echo "minor=$MINOR_TAG" >> "$GITHUB_OUTPUT"
  
        MAJOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1`;
        if ! [[ "$MAJOR_TAG" =~ ^v[0-9]$ ]]; then
          echo "::error::Invalid major tag format (expected vX) !"
          exit 3
        fi;
        echo "Major tag -> $MAJOR_TAG"
        echo "major=$MAJOR_TAG" >> "$GITHUB_OUTPUT"

    - shell: bash
      env:
        FULL_TAG: ${{ inputs.tag }}
        MINOR_TAG: ${{ steps.generate-tags.outputs.minor }}
        MAJOR_TAG: ${{ steps.generate-tags.outputs.major }}
      run: |
        # Create & push tags
        # /!\ Update the original tag at the end so it will be the latest tag generated, 
        # otherwise, github releases won't take it automatically as latest tag to automatically generate the changelog !
        git tag -f -a $MAJOR_TAG -m "Major tag for $FULL_TAG" && \
          git tag -f -a $MINOR_TAG -m "Minor tag for $FULL_TAG"   && \
          git tag -f -a $FULL_TAG -m "$FULL_TAG (see also $MAJOR_TAG or $MINOR_TAG)" && \
          git push origin --force $MINOR_TAG $MAJOR_TAG $FULL_TAG;
