.PHONY: all
all: build

.PHONY: install
install:
	yarn install

.PHONY: build
build:
	@echo "Nothing to build !"

.PHONY: compile
compile:
	@echo "Nothing to compile !"

.PHONY: lint
lint:
	@echo "Nothing to lint !"

.PHONY: test
test:
	@echo "Nothing to test !"
