.PHONY: all
all: build

.PHONY: install
install:
	yarn install

.PHONY: build
build: install package

.PHONY: package
package:
	@echo "Nothing to pack !"

.PHONY: lint
lint:
	@echo "Nothing to lint !"

.PHONY: test
test:
	@echo "Nothing to test !"
