name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          token: ${{ secrets.PUSH_TAGS_TOKEN }}

      - name: Generate vX and vX.Y tags
        uses: ./.github/actions/gha-versioning
        with:
          tag: ${{ github.event.release.tag_name }}
