name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Generate vX and vX.Y tags
        shell: bash
        env:
          FULL_TAG: ${{ github.event.release.tag_name }}
        run:
          ./workspace-utils/publish.sh $FULL_TAG
