name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Generate vX and vX.Y tags
        shell: bash
        env:
          FULL_TAG: ${{ github.event.release.tag_name }}
        run:
          
          if ! [[ "$FULL_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid tag format (expected vX.Y.Z) !"
            exit 1
          fi;

          MINOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1-2`;
          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid minor tag format (expected vX.Y) !"
            exit 2
          fi;

          MAJOR_TAG=`echo $FULL_TAG | cut -d '.' -f 1`;
          if ! [[ "$MINOR_TAG" =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid major tag format (expected vX) !"
            exit 3
          fi;
          
          git tag -f $MINOR_TAG && \
            git tag -f $MAJOR_TAG && \
            git push origin --force $MINOR_TAG $MAJOR_TAG;
